//League
export const GET_LEAGUE = 'GET_LEAGUE';
export const GET_LEAGUE_SUCCESS = 'GET_LEAGUE_SUCCESS';
export const GET_LEAGUE_FAILURE = 'GET_LEAGUE_FAILURE';

export const CREATE_LEAGUE = 'CREATE_LEAGUE';
export const CREATE_LEAGUE_SUCCESS = 'CREATE_LEAGUE_SUCCESS';
export const CREATE_LEAGUE_FAILURE = 'CREATE_LEAGUE_FAILURE';

export const UPDATE_LEAGUE = 'UPDATE_LEAGUE';
export const UPDATE_LEAGUE_SUCCESS = 'UPDATE_LEAGUE_SUCCESS';
export const UPDATE_LEAGUE_FAILURE = 'UPDATE_LEAGUE_FAILURE';


//ROUTES
export const SET_LEAGUE = 'SET_LEAGUE';
export const SET_LEAGUE_NAME_SUCCESS = 'SET_LEAGUE_NAME_SUCCESS';
export const SET_LEAGUE_NAME_FAILURE = 'SET_LEAGUE_NAME_FAILURE';


//Team
export const GET_TEAMS = 'GET_TEAMS';
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS';
export const GET_TEAMS_FAILURE = 'GET_TEAMS_FAILURE';

export const CREATE_TEAM = 'CREATE_TEAM';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const CREATE_TEAM_FAILURE = 'CREATE_TEAM_FAILURE';

export const DELETE_TEAM = 'DELETE_TEAM';
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS';
export const DELETE_TEAM_FAILURE = 'DELETE_TEAM_FAILURE';

export const UPDATE_PICK = 'UPDATE_PICK';
export const DELETE_PICK_SUCCESS = 'REMOVE_PICK_SUCCESS';
export const ADD_PICK_SUCCESS = 'ADD_PICK_SUCCESS';
export const UPDATE_PICK_FAILURE = 'UPDATE_PICK_FAILURE';



//PLayers
export const GET_PLAYERS = 'GET_PLAYERS';
export const GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS';
export const GET_PLAYERS_FAILURE = 'GET_PLAYERS_FAILURE';

export const DRAFT_PLAYER = 'DRAFT_PLAYER';
export const DRAFT_PLAYER_SUCCESS = 'DRAFT_PLAYER_SUCCESS';
export const DRAFT_PLAYER_FAILURE = 'DRAFT_PLAYER_FAILURE';

export const UNDRAFT_PLAYER = 'UNDRAFT_PLAYER';
export const UNDRAFT_PLAYER_SUCCESS = 'UNDRAFT_PLAYER_SUCCESS';
export const UNDRAFT_PLAYER_FAILURE = 'UNDRAFT_PLAYER_FAILURE';

//Data Actions
export const UPLOAD_DATA = 'UPLOAD_DATA';
export const UPLOAD_DATA_SUCCESS = 'UPLOAD_DATA_SUCCESS';
export const UPLOAD_DATA_FAILURE = 'UPLOAD_DATA_FAILURE';

export const DOWNLOAD_DRAFT = 'DOWNLOAD_DRAFT';
export const DOWNLOAD_DRAFT_SUCCESS = 'DOWNLOAD_DRAFT_SUCCESS';
export const DOWNLOAD_DRAFT_FAILURE = 'DOWNLOAD_DRAFT_FAILURE';

export const RESET_DB = 'RESET_DB';
export const RESET_DB_SUCCESS = 'RESET_DB_SUCCESS';
export const RESET_DB_FAILURE = 'RESET_DB_FAILURE';

export const SET_CONFIRM_DIALOG = 'SET_CONFIRM_DIALOG';
export const SET_CONFIRM_DIALOG_SUCCESS = 'SET_CONFIRM_DIALOG_SUCCESS';
export const SET_CONFIRM_DIALOG_FAILURE = 'SET_CONFIRM_DIALOG_FAILURE';

export const CONFIRM_DIALOG_RESULT = 'CONFIRM_DIALOG_RESULT';
export const CONFIRM_DIALOG_RESULT_SUCCESS = 'CONFIRM_DIALOG_RESULT_SUCCESS';
export const CONFIRM_DIALOG_RESULT_FAILURE = 'CONFIRM_DIALOG_RESULT_FAILURE';

export const RESET_ONFIRM_DIALOG = 'RESET_ONFIRM_DIALOG';
export const RESET_ONFIRM_DIALOG_SUCCESS = 'RESET_ONFIRM_DIALOG_SUCCESS';
export const RESET_ONFIRM_DIALOG_FAILURE = 'RESET_ONFIRM_DIALOG_FAILURE';
