// DRAFT/League
export const GET_DRAFT_SETTINGS_FAILURE = 'GET_DRAFT_SETTINGS_SUCCESS';
export const GET_DRAFT_SETTINGS_SUCCESS = 'GET_DRAFT_SETTINGS_FAILURE';
export const SET_DRAFT_PICK_SUCCESS = 'SET_DRAFT_PICK_SUCCESS';
export const SET_DRAFT_PICK_FAILURE = 'SET_DRAFT_PICK_FAILURE';

// ESPN
export const GET_PRIVATE_DRAFT_SUCCESS = 'GET_PRIVATE_DRAFT_SUCCESS';
export const GET_PRIVATE_DRAFT_FAILURE = 'GET_PRIVATE_DRAFT_FAILURE';

//League
export const GET_LEAGUE = 'GET_LEAGUE';
export const GET_LEAGUE_SUCCESS = 'GET_LEAGUE_SUCCESS';
export const GET_LEAGUE_FAILURE = 'GET_LEAGUE_FAILURE';

export const CREATE_LEAGUE = 'CREATE_LEAGUE';
export const CREATE_LEAGUE_SUCCESS = 'CREATE_LEAGUE_SUCCESS';
export const CREATE_LEAGUE_FAILURE = 'CREATE_LEAGUE_FAILURE';

export const UPDATE_LEAGUE = 'UPDATE_LEAGUE';
export const UPDATE_LEAGUE_SUCCESS = 'UPDATE_LEAGUE_SUCCESS';
export const UPDATE_LEAGUE_FAILURE = 'UPDATE_LEAGUE_FAILURE';


//ROUTES
export const SET_LEAGUE = 'SET_LEAGUE';
export const SET_LEAGUE_NAME_SUCCESS = 'SET_LEAGUE_NAME_SUCCESS';
export const SET_LEAGUE_NAME_FAILURE = 'SET_LEAGUE_NAME_FAILURE';


//PLayers
export const GET_NFL_TEAMS_SUCCESS = 'GET_NFL_TEAMS_SUCCESS';
export const GET_NFL_TEAMS_FAILURE = 'GET_NFL_TEAMS_FAILURE';
export const GET_POSITIONS_SUCCESS = 'GET_POSITIONS_SUCCESS';
export const GET_POSITIONS_FAILURE = 'GET_POSITIONS_FAILURE';
export const DRAFT_PLAYER_LIST_SUCCESS = 'DRAFT_PLAYER_LIST_SUCCESS';
export const DRAFT_PLAYER_LIST_FAILURE = 'DRAFT_PLAYER_LIST_FAILURE';
export const DRAFT_PLAYER_SUCCESS = 'DRAFT_PLAYER_SUCCESS';
export const DRAFT_PLAYER_FAILURE = 'DRAFT_PLAYER_FAILURE';

//Data Actions
export const UPLOAD_DATA = 'UPLOAD_DATA';
export const UPLOAD_DATA_SUCCESS = 'UPLOAD_DATA_SUCCESS';
export const UPLOAD_DATA_FAILURE = 'UPLOAD_DATA_FAILURE';

export const DOWNLOAD_DRAFT = 'DOWNLOAD_DRAFT';
export const DOWNLOAD_DRAFT_SUCCESS = 'DOWNLOAD_DRAFT_SUCCESS';
export const DOWNLOAD_DRAFT_FAILURE = 'DOWNLOAD_DRAFT_FAILURE';

export const RESET_DB = 'RESET_DB';
export const RESET_DB_SUCCESS = 'RESET_DB_SUCCESS';
export const RESET_DB_FAILURE = 'RESET_DB_FAILURE';

export const SET_CONFIRM_DIALOG = 'SET_CONFIRM_DIALOG';
export const SET_CONFIRM_DIALOG_SUCCESS = 'SET_CONFIRM_DIALOG_SUCCESS';
export const SET_CONFIRM_DIALOG_FAILURE = 'SET_CONFIRM_DIALOG_FAILURE';

export const CONFIRM_DIALOG_RESULT = 'CONFIRM_DIALOG_RESULT';
export const CONFIRM_DIALOG_RESULT_SUCCESS = 'CONFIRM_DIALOG_RESULT_SUCCESS';
export const CONFIRM_DIALOG_RESULT_FAILURE = 'CONFIRM_DIALOG_RESULT_FAILURE';

export const RESET_ONFIRM_DIALOG = 'RESET_ONFIRM_DIALOG';
export const RESET_ONFIRM_DIALOG_SUCCESS = 'RESET_ONFIRM_DIALOG_SUCCESS';
export const RESET_ONFIRM_DIALOG_FAILURE = 'RESET_ONFIRM_DIALOG_FAILURE';
